
package tibattlesim;

/**
 *
 * @author BoB
 */
public enum Race {
    
    FEDERATIONOFSOL, THEBARONYOFLETNEV, THEEMIRATESOFHACAN, SARDAKKNORR, 
    UNIVERSITIESOFJOLNAR, THEL1Z1XMINDNET, THEMENTAKCOALITION, THENAALUCOLLECTIVE,
    THEXXCHAKINGDOM, THEYSSARILTRIBES, THEWINNU, EMBERSOFMUAAT, THEYINBROTHERHOOD,
    THECLANOFSAAR, THEGHOSTSOFCREUSS, THENEKROVIRUS, THEARBOREC
    
}
